apiVersion: v1
kind: Pod
metadata:
  name: securitycontext-allowed-pod
spec:
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', "cat /message/message.txt && sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - name: message-volume
      mountPath: /message
  volumes:
  - name: message-volume
    hostPath:
      path: /tmp/message
---
apiVersion: v1
kind: Pod
metadata:
  name: securitycontext-unallowed-pod
spec:
  securityContext:
    runAsUser: 2001
    fsGroup: 3001
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', "cat /message/message.txt && sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - name: message-volume
      mountPath: /message
  volumes:
  - name: message-volume
    hostPath:
      path: /tmp/message