apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2  #Create max 2 further pods in the new replica set
      maxUnavailable: 10%  #Keep running at least 90% of total pods during update
      minReadySeconds: 0  #Seconds to wait before a Pod is considered available
      progressDeadlineSeconds: 60  #Wait period before a Deployment is considered failed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
