apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  sessionAffinity: ClientIP  #IP always connect to the same replica set during the rollout
  selector:
    app: nginx
    version: v1
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 80