apiVersion: v1
kind: Pod
metadata:
  name: pod-use-vol
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo -e "configmap:\n`cat /etc/config/configmap/game.properties`\n\nsecret:\n`cat /etc/config/secret/password`"']
    volumeMounts: # Each value is mounted as a separate file inside the mountPath
    - name: configmap-volume
      mountPath: /etc/config/configmap
    - name: secret-volume
      mountPath: /etc/config/secret
  volumes:
  - name: configmap-volume
    configMap:
      name: configmap
      items:
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"
  - name: secret-volume
    secret:
      secretName: secret
      optional: true # kubernetes ignores secret mount if it does not exist