apiVersion: v1
kind: Pod
metadata:
  name: pod-use-env
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo "configmap: $CONFIGMAPVAR secret: $SECRETVAR"']
    env:
      - name: CONFIGMAPVAR
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: player_initial_lives
      - name: SECRETVAR
        valueFrom:
          secretKeyRef:
            name: secret
            key: username