apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
spec:
  # nodeName: <node name>  # pod will be deployed on the specified node without leveraging kube-scheduler
  nodeSelector:
    node-label: selected 
  containers:
  - name: nginx
    image: nginx:1.19.1

#---
#apiVersion: v1
#kind: Node
#metadata:
#  name: node-label
#  labels:
#    node-label: selected