apiVersion: v1
kind: Service
metadata:
  name: lb-svc
spec:
  type: LoadBalancer
  #externalTrafficPolicy: local  # kube-proxy only selects pods inside the node
  #loadBalancerIP: 10.10.10.10  # You can specify the load balancer IP you want to assign
  selector:
    name: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
