apiVersion: v1
kind: Service
metadata:
  name: node-port-svc
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30100  # Port from Node IP to communicate with Cluster IP