apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    livenessProbe:
      exec:
        command: ["echo", "Hello, world!"] # disgnostic is successfull if commands exits with code 0
      initialDelaySeconds: 5  # how much wait before performing the first check
      periodSeconds: 5  # how often kubelet performs the check