apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: allowed-ns
  name: pod-reader-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-role.binding
  namespace: default
subjects:
- kind: User  # Or ServiceAccount
  name: allowed-user
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io