apiVersion: v1
kind: Namespace
metadata:
  name:  rbac-ns
---
apiVersion: rbac.authorization.k8s.io/v1
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allowed-sa
  namespace: rbac-ns
---
apiVersion: rbac.authorization.k8s.io/v1
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unallowed-sa
  namespace: rbac-ns