apiVersion: v1
kind: Pod
metadata:
  name: pod-no-token
spec:
  serviceAccountName: test-sa
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-token
spec:
  serviceAccountName: test-sa
  automountServiceAccountToken: true # default behaviour
  containers:
  - name: nginx
    image: nginx