apiVersion: v1
kind: Pod
metadata:
  name: allowed-pod
  namespace: rbac-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
---
apiVersion: v1
kind: Pod
metadata:
  name: unallowed-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1